PTR-11 Create AnnotatedBeanDefinitionReader
petrosteam/bring-ioc pull request #5
Opened 2023-01-25 17:22 UTC by mitssev

2023-01-26 19:08 UTC, mykolad4 requested changes
To my mind, PR can be merged. All that refers to architecture, will be refactored later. We should start from something. Just fix test with Optional.

2023-01-26 19:08 UTC, mykolad4 commented on src/main/java/com/pertos/bring/annotations/Component.java
> +@Target({ElementType.TYPE, ElementType.METHOD})
I thought that @Bean should be used on methods in @Configuration classes. Where can we use @Component annotation on method?

2023-01-26 19:08 UTC, mykolad4 commented on src/main/java/com/pertos/bring/reader/impl/AnnotatedBeanDefinitionReader.java
> +        beanDefinitionRegistry = new BeanDefinitionRegistryImpl(new HashSet<>());
I think it's better idea not to make Reader as Registry owner. It supposed that our application will contain more than one Reader (Annotation, Json, Java...) and every Reader will fill a single Registry with BeanDefinitions. Current implementation not seems as extendable. In general, I thought application will look the next way:
```
void main() {
  Registry registry = createRegistry();
  Set<Reader> readers = registerReaders(registry);
  readers.forEach(Reader::loadBeanDefinitions);
  Application context = new ApplicationContext(registry);
  context.createBeans();
  Set<BeanPostProcessor> processors = registerProcessors();
  processors.forEach(processor -> processor.processBeforeInitialization(context.getAllBeans()));
  processors.forEach(processor -> processor.processAfterInitialization(context.getAllBeans()));
} 
```

2023-01-26 19:08 UTC, mykolad4 commented on src/main/java/com/pertos/bring/reader/impl/AnnotatedBeanDefinitionReader.java
> +                .filter(method -> method.isAnnotationPresent(Component.class))
We should use @Bean annotation instead of @Component in @Configuration classes

2023-01-26 19:08 UTC, mykolad4 commented on src/main/java/com/pertos/bring/reader/impl/AnnotatedBeanDefinitionReader.java
> +    private boolean isPrimary(Method method) {
When we divide Reader into two classes (AnnotationBeanDefinitionReader and JavaBeanDefinitionReader) allows us to rid off duplicate methods in single class isLazy, isPrimary...

2023-01-26 19:08 UTC, mykolad4 commented on src/main/java/com/pertos/bring/reader/impl/BeanDefinitionImpl.java
> +        public static BeanDefinitionBuilder newInstance() {
Why don't use usual methods naming in Builder pattern?
```
BeanDefinitionBuilder.builder()
                    ...
                    .build()
```

2023-01-26 19:08 UTC, mykolad4 commented on src/test/java/com/pertos/bring/test/AnnotatedBeanDefinitionReaderTest.java
> +        assertThat(Optional.ofNullable(beanDefinitionReader)).isNotNull();
The result is always true, because ofNullable returns Optional object, it cannot return null.
You imported package org.junit.jupiter.api.*. It contains method assertNotNull, so this test could be rewritten as follow:
`assertNotNull(beanDefinitionReader);`
But it is up to you what methods to use for assertions. Assertj is also fine. Just remove Optional part.

2023-01-26 20:09 UTC, mitssev commented on src/test/java/com/pertos/bring/test/AnnotatedBeanDefinitionReaderTest.java
> +        assertThat(Optional.ofNullable(beanDefinitionReader)).isNotNull();
fixed

2023-01-26 20:20 UTC, mykolad4 approved these changes

2023-01-27 17:31 UTC, artem-dehnych approved these changes

2023-01-27 18:21 UTC, merged